
namespace Desafio_1._2.Exceptions
{
    internal class NotFindAttendaceException : Exception
    {
        public NotFindAttendaceException() : base("ERROR: Consulta inexistente") { }
    }
}
